### ISSUE TITLE
Server fails to launch

### ISSUE THREAD

**Issue by Jonathan-L-Davis** [Noeli14/MCppServer#2]
After building the server, it did not seem to connect to the auth server the first 2 times it ran.

```
user@machine:~/some/dir/MCppServer/build$ ./MCppServer
[DEBUG] Created default level.dat.
[INFO] Server started in 138 ms
[INFO] Minecraft server is running on port 25565
[ERROR] Authentication request failed: No response from session server.
stop
[ERROR] [Console] Unknown command or invalid arguments.
^C
```
Is there some set up I am missing or is this caused by a bug?<br>
I have tried to log in with both a 1.21.1 client and a 1.21.4 client.

**Comment by Jonathan-L-Davis** [comment]
I could have chosen a better title, the error is actually the client and or server fails to Authenticate.

**Comment by Noeli14** [comment]
Are you running the server on Linux? The authentication is currently not working on Linux. You can turn off online mode, than you will be able to join. Web fetches are not working on Linux, so skins will also not work. But I am trying to fix this.
